language: node_js
node_js:
  - 12

install: npm install

jobs:
  include:
    - stage: npm test & release
      node_js: 12
      script:
        - npm test
        - npm run build
        - echo "Deploying to npm!"
      deploy:
        provider: npm
        email: cgs.camilogonzalez@gmail.com
        api_key: $NPM_API_KEY
        on:
          branch: master
